"""LoRA fine-tuning of small local LLMs on multi-turn tool-calling dialogues.

The root package stays free of torch; training lives in ``toolcall_sft.training``
and is pulled in only by the ``tcsft-train`` CLI. transformers is needed at
runtime only where a tokenizer is actually used (``masking``, ``stats``).
"""

from .anonymizer import AnonymizationReport, Anonymizer
from .config import (
    DEFAULT_CHAT_TEMPLATE_KWARGS,
    LR_SCHEDULERS,
    ConfigError,
    DatasetSettings,
    ExperimentConfig,
    LoraSettings,
    TrackingSettings,
    TrainingSettings,
    flatten_for_logging,
    load_experiment_config,
)
from .dataset import (
    DatasetSplit,
    DatasetStats,
    dataset_stats,
    dedup_dialogues,
    load_dialogues,
    split_dialogues,
    write_dialogues,
)
from .generate import BRANCH_WEIGHTS, GenerationError, branch_names, generate_dialogues
from .masking import (
    LABEL_IGNORE_INDEX,
    MaskedExample,
    TemplateCompatibilityError,
    render_example,
    tokenize_dialogue,
)
from .metrics import (
    CallTotals,
    GroupReport,
    ToolCallComparison,
    ToolCallReport,
    ToolReport,
    TurnRecord,
    branch_of,
    compare_tool_calls,
    evaluate_turns,
    format_report,
)
from .parsing import (
    TOOL_CALL_CLOSE,
    TOOL_CALL_OPEN,
    ParsedTurn,
    check_tool_call,
    check_tool_calls,
    parse_assistant_output,
)
from .scenario import SYSTEM_PROMPT, TOOLS, tool_names
from .schema import (
    DatasetError,
    Dialogue,
    Message,
    Role,
    ToolCall,
    chat_messages,
    content_fingerprint,
    dialogue_from_json,
    dialogue_to_json,
    to_chat_record,
)
from .stats import (
    DEFAULT_THRESHOLDS,
    HISTOGRAM_EDGES,
    DialogueTokenCount,
    LengthFilterResult,
    TokenStatsReport,
    compute_token_stats,
    filter_by_length,
    histogram,
    percentile,
    threshold_fits,
)

__all__ = [
    "BRANCH_WEIGHTS",
    "DEFAULT_CHAT_TEMPLATE_KWARGS",
    "DEFAULT_THRESHOLDS",
    "HISTOGRAM_EDGES",
    "LABEL_IGNORE_INDEX",
    "LR_SCHEDULERS",
    "SYSTEM_PROMPT",
    "TOOL_CALL_CLOSE",
    "TOOL_CALL_OPEN",
    "TOOLS",
    "AnonymizationReport",
    "Anonymizer",
    "CallTotals",
    "ConfigError",
    "DatasetError",
    "DatasetSettings",
    "DatasetSplit",
    "DatasetStats",
    "Dialogue",
    "DialogueTokenCount",
    "GenerationError",
    "GroupReport",
    "LengthFilterResult",
    "ExperimentConfig",
    "LoraSettings",
    "MaskedExample",
    "Message",
    "ParsedTurn",
    "Role",
    "TemplateCompatibilityError",
    "TokenStatsReport",
    "ToolCall",
    "ToolCallComparison",
    "ToolCallReport",
    "ToolReport",
    "TrackingSettings",
    "TrainingSettings",
    "TurnRecord",
    "branch_names",
    "branch_of",
    "chat_messages",
    "check_tool_call",
    "check_tool_calls",
    "compare_tool_calls",
    "compute_token_stats",
    "content_fingerprint",
    "dataset_stats",
    "dedup_dialogues",
    "dialogue_from_json",
    "dialogue_to_json",
    "evaluate_turns",
    "filter_by_length",
    "flatten_for_logging",
    "format_report",
    "generate_dialogues",
    "histogram",
    "load_dialogues",
    "load_experiment_config",
    "parse_assistant_output",
    "percentile",
    "render_example",
    "split_dialogues",
    "threshold_fits",
    "to_chat_record",
    "tokenize_dialogue",
    "tool_names",
    "write_dialogues",
]
